REPLACE_TRIGGER_TEXT ~Nalia~ ~OR(2)[%BLANK%]Class(Player1,FIGHTER_ALL)[%BLANK%]Kit(Player1,Blackguard)~
	~OR(3)
	Class(Player1,FIGHTER_ALL)
	Kit(Player1,Blackguard)
	CheckStatGT(Player1,2,PROFICIENCY2WEAPON)~
	
REPLACE_TRIGGER_TEXT ~NaliaJ~ ~OR(2)[%BLANK%]Class(Player1,FIGHTER_ALL)[%BLANK%]Kit(Player1,Blackguard)~
	~OR(3)
	Class(Player1,FIGHTER_ALL)
	Kit(Player1,Blackguard)
	CheckStatGT(Player1,2,PROFICIENCY2WEAPON)~