DEFINE_ACTION_FUNCTION ~APPEND_SPLSTATE~	// 向SPLSTATE.ids中添加splstate_name
	STR_VAR splstate_name = ~~
	RET i
BEGIN

COPY_EXISTING ~SPLSTATE.ids~ ~Override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	SPRINT indexes ~~
	FOR (i = 1; i < rows; ++i) BEGIN
		READ_2DA_ENTRY i 0 cols index
		SPRINT indexes ~%indexes%~^~%index% ~
	END
	i = 1
	WHILE (! ~%indexes%~ STRING_CONTAINS_REGEXP ~%i%~) BEGIN
		i = i+1
	END
	INSERT_2DA_ROW rows cols ~%i% %splstate_name%~
	PRETTY_PRINT_2DA
	BUT_ONLY

END