OUTER_SPRINT ~BLANK~ ~%TAB%%MNL%%LNL% ~

// 1
// SOD到SOA物品继承
ACTION_IF GAME_IS ~eet~ BEGIN
	COPY_EXISTING ~K#TELBGT.bcs~ ~override~		// 阻止SOD结局伏击场景取走玩家一些特定物品（主要是SOD物品，取走以后会分散到SOA中）
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~TakePartyItem(.*)[%BLANK%]*DestroyItem(.*)[%BLANK%]*AddStoreItem(.*)~
				~~
		END
	BUT_ONLY

	EXTEND_BOTTOM ~AR0602.bcs~ ~%MOD_FOLDER%\BAF\AR0602.baf~	// 把 K#ImportContainer 中的物品转移到 Chest1（依力奇附近的箱子）
	EXTEND_BOTTOM ~AR0301.bcs~ ~%MOD_FOLDER%\BAF\AR0301.baf~	// 把储存在变量 K#ImportGold 中的钱转移到麦瓦
	
	COPY_EXISTING ~AR0500.bcs~ ~override~		// 阻止大桥区初始化涅拉装备
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Neera",DestroyAllEquipment())~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Neera",CreateItem(.*,1,0,0))~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Neera",FillSlot(.*))~
				~~
		END
	BUT_ONLY
	
	COPY_EXISTING ~AR0900.bcs~ ~override~		// 阻止神殿区初始化多恩装备
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Dorn",DestroyAllEquipment())~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Dorn",CreateItem(.*,1,0,0))~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Dorn",FillSlot(.*))~
				~~
		END
	BUT_ONLY
	
	COPY_EXISTING ~AR1000.bcs~ ~override~		// 阻止行政区初始化维康尼亚装备
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Viconia",DestroyAllEquipment())~
				~ActionOverride("Viconia",DropInventory())~
		END
	BUT_ONLY
	
	COPY_EXISTING ~AR2000.bcs~ ~override~		// 阻止崔米镇初始化拉萨德装备
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Rasaad",DestroyAllEquipment())~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Rasaad",CreateItem(.*,1,0,0))~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Rasaad",FillSlot(.*))~
				~~
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~ActionOverride("Rasaad",EquipMostDamagingMelee())~
				~~
		END
	BUT_ONLY
END

// 2
// 据点条件放宽
COMPILE ~%MOD_FOLDER%/Dialogues/Stronghold.d~

ACTION_IF GAME_IS ~eet~ BEGIN
	COPY_EXISTING ~Nalia.dlg~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~OR(2)[%BLANK%]Class(Player1,FIGHTER_ALL)[%BLANK%]Kit(Player1,Blackguard)~
				~OR(3)
					Class(Player1,FIGHTER_ALL)
					Kit(Player1,Blackguard)
					CheckStatLT(Player1,11,THAC0)~
		END
	BUT_ONLY
	
	COPY_EXISTING ~NaliaJ.dlg~ ~override~
		DECOMPILE_AND_PATCH BEGIN
			REPLACE_TEXTUALLY CASE_INSENSITIVE EVALUATE_REGEXP
				~OR(2)[%BLANK%]Class(Player1,FIGHTER_ALL)[%BLANK%]Kit(Player1,Blackguard)~
				~OR(3)
					Class(Player1,FIGHTER_ALL)
					Kit(Player1,Blackguard)
					CheckStatLT(Player1,11,THAC0)~
		END
	BUT_ONLY
END
