INCLUDE ~%MOD_FOLDER%\LIB\APPEND_SPLSTATE.tph~
INCLUDE ~%MOD_FOLDER%\LIB\APPEND_SPLPROT.tph~

LOAD_TRA ~%MOD_FOLDER%\TRA\%LANGUAGE%\Game.tra~

// lua相关
ACTION_IF !FILE_EXISTS_IN_GAME ~ST_Tweak.lua~ BEGIN	// 检测同mod其它组件是否已安装
	COPY ~%MOD_FOLDER%\LUA\ST_Tweak.lua~ ~Override~
	COPY_EXISTING ~M_Stick.lua~ ~Override~
		APPEND_FILE ~%MOD_FOLDER%\LUA\ToAppend.lua~
END
COPY_EXISTING ~ST_Tweak.lua~ ~Override~
	APPEND_FILE ~%MOD_FOLDER%\LUA\SpellTweak.lua~

// 1
// 真视每秒生效
	// 定义函数
DEFINE_ACTION_FUNCTION ~ALTER_TRUESS~
	STR_VAR spell_name = ~~ 2nd_spell_name = EVAL ~%spell_name%D~
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%spell_name%.spl~ BEGIN
		COPY_EXISTING ~%spell_name%.spl~ ~Override~
			READ_LONG 0x34 spell_level
			LPF DELETE_SPELL_EFFECT
				INT_VAR opcode_to_delete = 146
			END
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 333 target = 1 power = spell_level parameter1 = 60 parameter2 = 1 timing = 3 duration =1 special = 1
				STR_VAR resource = EVAL ~%2nd_spell_name%~
			END
		ACTION_IF FILE_EXISTS_IN_GAME ~%2nd_spell_name%.spl~ BEGIN
			COPY_EXISTING ~%2nd_spell_name%.spl~ ~Override~
				WRITE_LONG 0x08 0xFFFFFFFF
			BUT_ONLY
		END
	END
END
	// 调用函数
LAF ALTER_TRUESS
	STR_VAR spell_name = ~SPCL232~
END
LAF ALTER_TRUESS
	STR_VAR spell_name = ~SPCL732~ 2nd_spell_name = ~SPPR950~
END
LAF ALTER_TRUESS
	STR_VAR spell_name = ~SPPR505~
END
LAF ALTER_TRUESS
	STR_VAR spell_name = ~SPWI609~
END
	// 修改说明
COPY_EXISTING ~SPPR505.spl~ ~Override~
	READ_LONG 0x50 unidf_desc
STRING_SET_EVALUATE unidf_desc @30011
ALTER_TLK_LIST BEGIN unidf_desc END BEGIN END
COPY_EXISTING ~SPWI609.spl~ ~Override~
	READ_LONG 0x50 unidf_desc
STRING_SET_EVALUATE unidf_desc @30012
ALTER_TLK_LIST BEGIN unidf_desc END BEGIN END

// 2
// 刀阵每秒生效
	// 定义函数
DEFINE_ACTION_FUNCTION ~ALTER_BLADEBG~
	INT_VAR dice_number_1 = 1 dice_number_2 = 1 dice_number_3 = 1 dice_size = 0 save_bonus = 0
	STR_VAR spell_name = ~~ 2rd_spell_name = EVAL ~%spell_name%D~
BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%spell_name%.spl~ BEGIN
		COPY_EXISTING ~%spell_name%.spl~ ~Override~
			READ_LONG 0x34 spell_level
			LPF DELETE_SPELL_EFFECT
				INT_VAR opcode_to_delete = 177
			END
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 333 target = 1 power = spell_level parameter1 = 60 parameter2 = 1 special = 1
				STR_VAR resource = EVAL ~%spell_name%A~
			END
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 333 target = 1 power = spell_level parameter1 = 60 parameter2 = 1 special = 1
				STR_VAR resource = EVAL ~%spell_name%B~
			END
		COPY_EXISTING ~%2rd_spell_name%.spl~ ~Override\%spell_name%D.spl~
		COPY ~%MOD_FOLDER%\SPL\BLADEBGA.spl~ ~Override\%spell_name%A.spl~	// （每秒触发）造成伤害，目标移动时触发%spell_name%C.spl
			WRITE_LONG 0x34 spell_level
			LPF ALTER_SPELL_EFFECT
				INT_VAR match_opcode = 366
				STR_VAR resource = EVAL ~%spell_name%C~
			END
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 12 target = 2 parameter2 = 0x01000000 probability1 = 33 dicenumber = dice_number_1 dicesize = dice_size
					savingthrow = 0x1000001 savebonus = save_bonus
			END
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 12 target = 2 parameter2 = 0x01000000 probability2 = 34 dicenumber = dice_number_2 dicesize = dice_size
					savingthrow = 0x1000001 savebonus = save_bonus
			END
		COPY ~%MOD_FOLDER%\SPL\BLADEBGB.spl~ ~Override\%spell_name%B.spl~	// （每秒触发）自身移动时触发%spell_name%D.spl
			WRITE_LONG 0x34 spell_level
			LPF ALTER_SPELL_EFFECT
				INT_VAR match_opcode = 366
				STR_VAR resource = EVAL ~%spell_name%D~
			END	
		COPY ~%MOD_FOLDER%\SPL\BLADEBGC.spl~ ~Override\%spell_name%C.spl~	// （目标移动时触发）造成伤害，瞬间免疫%spell_name%D.spl
			WRITE_LONG 0x34 spell_level
			LPF ALTER_SPELL_EFFECT
				INT_VAR match_opcode = 12 dicenumber = dice_number_3 dicesize = dice_size savebonus = save_bonus
			END
			LPF ALTER_SPELL_EFFECT
				INT_VAR match_opcode = 206
				STR_VAR resource = EVAL ~%spell_name%D~
			END
		COPY_EXISTING ~%spell_name%D.spl~ ~Override~	// （自身移动时触发）造成伤害，瞬间免疫%spell_name%C.spl
			WRITE_LONG 0x08 0xFFFFFFFF
			WRITE_LONG 0x34 spell_level
			LPF ADD_SPELL_EFFECT
				INT_VAR opcode = 206 target = 2
				STR_VAR resource = EVAL ~%spell_name%C~
			END
	END
END
	// 调用函数
LAF ALTER_BLADEBG
	INT_VAR dice_number_1 = 2 dice_number_3 = 8 dice_size = 8
	STR_VAR spell_name = ~MELIS02~ 2rd_spell_name = ~MELIS02B~
END
LAF ALTER_BLADEBG
	INT_VAR dice_number_1 = 2 dice_number_3 = 8 dice_size = 8
	STR_VAR spell_name = ~SPPR603~
END
LAF ALTER_BLADEBG
	INT_VAR dice_number_1 = 2 dice_number_3 = 8 dice_size = 8
	STR_VAR spell_name = ~SPPR698~
END
LAF ALTER_BLADEBG
	INT_VAR dice_number_2 = 2 dice_number_3 = 10 dice_size = 10 save_bonus = 0xfffffffe
	STR_VAR spell_name = ~SPPR725~
END
	// 修改说明
COPY_EXISTING ~SPPR603.spl~ ~Override~
	READ_LONG 0x50 unidf_desc
STRING_SET_EVALUATE unidf_desc @30021
ALTER_TLK_LIST BEGIN unidf_desc END BEGIN END
COPY_EXISTING ~SPPR725.spl~ ~Override~
	READ_LONG 0x50 unidf_desc
STRING_SET_EVALUATE unidf_desc @30022
ALTER_TLK_LIST BEGIN unidf_desc END BEGIN END

// 3
// 协同防御
LAF APPEND_SPLPROT
	INT_VAR stat = 133 value = 0xFFFFFFFF relation = 4
	STR_VAR name = ~CLERIC_DEFENSIVE_HARMONY>=n~
	RET DH_index_1 = index
END
LAF APPEND_SPLPROT
	INT_VAR stat = 133 value = 0xFFFFFFFF relation = 2
	STR_VAR name = ~CLERIC_DEFENSIVE_HARMONY<n~
	RET DH_index_2 = index
END
COPY ~%MOD_FOLDER%\SPL\SPPR406.spl~ ~Override~	// 对范围内目标施放 SPPR406A.spl
	READ_LONG 0x50 unidf_desc
STRING_SET_EVALUATE unidf_desc @3003
ALTER_TLK_LIST BEGIN unidf_desc END BEGIN END
COPY ~%MOD_FOLDER%\SPL\SPPR406A.spl~ ~Override~	// 每轮对自身施放 SPPR406B.spl
COPY ~%MOD_FOLDER%\SPL\SPPR406B.spl~ ~Override~	// 自身AC-1；对所有人条件判定：友方阵营时调用 SPPR406C.spl
COPY ~%MOD_FOLDER%\SPL\SPPR406C.spl~ ~Override~	// 条件判定：CLERIC_DEFENSIVE_HARMONY>=1时调用 SPPR406D.spl
	LPF ALTER_SPELL_EFFECT
		INT_VAR match_opcode = 326 parameter2 = DH_index_1
	END
COPY ~%MOD_FOLDER%\SPL\SPPR406D.spl~ ~Override~	// 条件判定，CLERIC_DEFENSIVE_HARMONY<7时调用 SPPR406E.spl
	LPF ALTER_SPELL_EFFECT
		INT_VAR match_opcode = 326 parameter2 = DH_index_2
	END
COPY ~%MOD_FOLDER%\SPL\SPPR406E.spl~ ~Override~	// CLERIC_DEFENSIVE_HARMONY+1，AC+1

// 4
// 自由行动不免疫加速
COPY_EXISTING ~SPPR403.spl~ ~override~
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 101 match_parameter2 = 16
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 126 match_parameter1 = 100 match_parameter2 = 2
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 169 match_parameter2 = 38
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPRA301~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPIN572~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPIN828~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPCL522~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPWI305~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 206
		STR_VAR match_resource = ~SPWI613~
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 240 match_parameter2 = 38
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 240 match_parameter2 = 195
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 267 match_parameter1 = 10954
	END
	LPF DELETE_EFFECT
		INT_VAR match_opcode = 267 match_parameter1 = 14023
	END
	BUT_ONLY
	
// 5
COPY_EXISTING_REGEXP ~.*\.spl~ ~Override~
	READ_SHORT 0x1c spell_type
	PATCH_IF (spell_type = 1) OR (spell_type = 2) BEGIN
		READ_SHORT 0x68 num
		PATCH_IF num > 0 BEGIN
			READ_SHORT 0x7e target
			PATCH_IF target = 5 BEGIN
				LPF ALTER_SPELL_HEADER
					INT_VAR range  = 40
				END
			END
		END
		
	END

// 火盾被攻击未命中也生效
COPY ~%MOD_FOLDER%\EFF\SPCL237D.eff~ ~override~
COPY ~%MOD_FOLDER%\EFF\SPWI403D.eff~ ~override~
COPY ~%MOD_FOLDER%\EFF\SPWI418D.eff~ ~override~
COPY ~%MOD_FOLDER%\EFF\SPPR730D.eff~ ~override~
