DEFINE_ACTION_FUNCTION ~APPEND_SPLPROT~	// 向 SPLPROT.2da中添加判定
	INT_VAR stat = 0	value = 0	relation = 0
	STR_VAR name = ~~
	RET index
BEGIN

COPY_EXISTING ~SPLPROT.2da~ ~Override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	splprot_exist = 0
	FOR (i = 1; i < rows; ++i) BEGIN
		READ_2DA_ENTRY i 1 cols stat_temp
		READ_2DA_ENTRY i 2 cols value_temp
		READ_2DA_ENTRY i 3 cols relation_temp
		PATCH_IF !(~%value_temp%~ STRING_MATCHES_REGEXP ~[0-9]~) BEGIN
			PATCH_IF (stat = stat_temp & value = value_temp & relation = relation_temp) BEGIN
				index = i
				splprot_exist = 1
			END
		END	
	END
	PATCH_IF splprot_exist = 0 BEGIN
		INSERT_2DA_ROW rows cols ~%rows%_%name% %stat% %value% %relation%~
		index = rows
		PRETTY_PRINT_2DA
	END
END